version: "3.3"
services:
  postgres:
    image: postgres:15.5
    networks:
      - webnet
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgresdata:/var/lib/postgresql/data

  redis:
    image: "redis:6.2.13-alpine3.18"
    networks:
      - webnet
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redisdata:/bitnami/redis/data

  backend:
    image: "ghcr.io/robiot/notan-backend:latest"
    networks:
      - webnet
    depends_on:
      - postgres
      - redis
    tty: true
    environment:
      - PORT=8000
      - LOG_LEVEL=trace,backend=trace
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}

  notangrafana:
    image: grafana/grafana:9.3.6
    networks:
      - webnet
    ports:
      - "3000:3000"
    volumes:
      - grafanadata:/var/lib/grafana

  backup:
    image: jareware/docker-volume-backup
    networks:
      - webnet
    environment:
      AWS_S3_BUCKET_NAME: notan-backup
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_EXTRA_ARGS: --endpoint-url https://${AWS_R2_USER}.r2.cloudflarestorage.com
      BACKUP_FILENAME: latest.tar.gz
    volumes:
      - grafanadata:/backup/grafana-data:ro
      - postgresdata:/backup/postgres-data:ro

networks:
  webnet:
    external:
      name: webnet-a

volumes:
  postgresdata:
  redisdata:
  grafanadata:
