version: '3.9'
services:
  postgres:
      image: postgres
      profiles: ["services"]
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=root
      volumes:
        - ./data/postgres:/var/lib/postgresql/data

  redis:
      image: "redis:6.2.13-alpine3.18"
      profiles: ["services"]
      environment:
          - ALLOW_EMPTY_PASSWORD=yes
      volumes:
          - ./data/redis:/bitnami/redis/data
      ports:
          - "6379:6379"

  backend:
      build: services/backend
      profiles: ["backend"]
      volumes:
        - ./services/backend:/usr/src/app
        - backend-target:/usr/src/app/target
      depends_on:
        - postgres
        - redis
      ports:
        - "8000:8000"
      tty: true
      environment:
        - PORT=8000
        - LOG_LEVEL=info,backend=info

        - DATABASE_URL=postgres://postgres:root@postgres:5432/postgres
        - REDIS_URL=redis://redis:6379
        - JWT_SECRET=${JWT_SECRET}
      command: cargo watch -x run

volumes:
  backend-target:
