version: '3.9'
services:
  postgres:
      image: postgres:15.5
      profiles: ["services", "all"]
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=root
      volumes:
        - ./data/postgres:/var/lib/postgresql/data

  redis:
      image: "redis:6.2.13-alpine3.18"
      profiles: ["services", "all"]
      environment:
          - ALLOW_EMPTY_PASSWORD=yes
      volumes:
          - ./data/redis:/bitnami/redis/data
      ports:
          - "6379:6379"

  stripe-cli:
    image: stripe/stripe-cli
    network_mode: host
    profiles: ["all"]
    container_name: stripe-cli
    command: "listen --api-key ${STRIPE_SECRET_KEY} --device-name docker --forward-to 0.0.0.0:8000/payments/webhook"

  backend:
      build: services/backend
      profiles: ["backend", "all"]
      volumes:
        - ./services/backend:/usr/src/app
        - backend-target:/usr/src/app/target
      depends_on:
        - postgres
        - redis
      ports:
        - "8000:8000"
      tty: true
      environment:
        - PORT=8000
        - LOG_LEVEL=trace,backend=trace
        - DATABASE_URL=postgres://postgres:root@postgres:5432/postgres
        - REDIS_URL=redis://redis:6379
        - JWT_SECRET=${JWT_SECRET}
        - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
        - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      command: cargo watch -x run

volumes:
  backend-target:
