export const enviroment = {
  API_URL: process.env.NEXT_PUBLIC_API_URL!,
  SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN!,
  STRIPE_PUBLIC_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLIC_KEY!,
  GOOGLE_OAUTH_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID!,
};
