name: Build Backend

on:
  push:
    tags:
      - "backend-*"

jobs:
  build:
    runs-on: ARM64
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Set Tag without "backend-"
        id: set_tag
        run: echo "tag=$(echo ${{ github.ref }} | sed 's/^refs\/tags\/backend-//')" >> $GITHUB_STATE

      # --- Prepare Docker ---
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/robiot/notan-backend
          tags: |
            type=semver,value=v1.0.2
            type=edge

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          platforms: linux/arm64
          file: services/backend/Dockerfile.prod
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
